### ISSUE TITLE
17版本无法启动

### ISSUE THREAD

**Issue by Guodun** [Terry-Su/debug-react-source-code#3]
Hi，16版本按文档可以正常启动，17版本不行哦。

**Comment by Terry-Su** [comment]
@Guodun 感谢提醒，已更新（问题出在6000端口一般会被占用）

**Comment by bihongbin3027** [comment]
@Terry-Su 17.0 版本
npm install
npm start 无法启动

**Comment by Terry-Su** [comment]
@bihongbin3027  cd 到对应目录即可，已修复
