### ISSUE TITLE
16.13.1使用hooks报错

### ISSUE THREAD

**Issue by robertYang1024** [Terry-Su/debug-react-source-code#6]
分支是debug-react-16.13.1，使用React.useState后报错，换成useState也不行，希望有空的话，能帮忙看一下

17.0.0分支是可以的
```jsx
function App() {
    const [num, setNum] = React.useState(0)
    return <div>
                {num} 
                <button onClick={() => setNum(num => num+1)}>add</button>
            </div>
}

ReactDOM.render(<App/>, document.querySelector('#app'))
```

报错如下：
![Snipaste_2021-06-22_19-28-32](https://user-images.githubusercontent.com/24569873/122916981-1706b900-d390-11eb-8bde-3bb227e462fe.png)

**Comment by Terry-Su** [comment]
@Genitana 
我本地测试16.13.1可以运行，你再检查下
https://github.com/Terry-Su/debug-react-source-code/blob/debug-react-16.13.1/react-16.13.1/index.js

**Comment by robertYang1024** [comment]
我试了下，16.13.1确实可以，可能是我之前哪里弄错了，我把问题关了，感谢回复
