### ISSUE TITLE
18.0.1 改了index.js里的代码，再次debugger，仍然还是上次的旧代码。不管多少次重新启动debugger还是一样的。

### ISSUE THREAD

**Issue by wangxingxing123654** [Terry-Su/debug-react-source-code#9]
`'use strict';

var _React = React,
    useEffect = _React.useEffect,
    useRef = _React.useRef;

function App() {
    var ref = useRef(null);

    useEffect(function () {
        debugger;
        // beforeActivate
        console.log(123);
        ref.current.focus();
    }, []);
    return React.createElement(
        'div',
        null,
        React.createElement('input', { ref: ref }),
        React.createElement(
            'p',
            null,
            'Hello, React Source Code!'
        ),
        React.createElement(
            'h3',
            null,
            'Hello, React Source Code!',
            React.createElement(
                'span',
                null,
                '123'
            )
        )
    );
}

ReactDOM.render(React.createElement(App, null), document.querySelector('#app'));
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImluZGV4LmpzIl0sIm5hbWVzIjpbIlJlYWN0IiwidXNlRWZmZWN0IiwidXNlUmVmIiwiQXBwIiwicmVmIiwiY29uc29sZSIsImxvZyIsImN1cnJlbnQiLCJmb2N1cyIsIlJlYWN0RE9NIiwicmVuZGVyIiwiZG9jdW1lbnQiLCJxdWVyeVNlbGVjdG9yIl0sIm1hcHBpbmdzIjoiOzthQUMyQkEsSztJQUFwQkMsUyxVQUFBQSxTO0lBQVVDLE0sVUFBQUEsTTs7O0FBSWpCLFNBQVNDLEdBQVQsR0FBZTtBQUNYLFFBQU1DLE1BQU1GLE9BQU8sSUFBUCxDQUFaOztBQUVGRCxjQUFVLFlBQU07QUFDZDtBQUNBO0FBQ0FJLGdCQUFRQyxHQUFSLENBQVksR0FBWjtBQUNBRixZQUFJRyxPQUFKLENBQVlDLEtBQVo7QUFDRCxLQUxELEVBS0csRUFMSDtBQU1FLFdBQU87QUFBQTtBQUFBO0FBQ0gsdUNBQU8sS0FBS0osR0FBWixHQURHO0FBRUg7QUFBQTtBQUFBO0FBQUE7QUFBQSxTQUZHO0FBR0g7QUFBQTtBQUFBO0FBQUE7QUFBNkI7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUE3QjtBQUhHLEtBQVA7QUFLSDs7QUFFREssU0FBU0MsTUFBVCxDQUFnQixvQkFBQyxHQUFELE9BQWhCLEVBQXdCQyxTQUFTQyxhQUFULENBQXVCLE1BQXZCLENBQXhCIiwiZmlsZSI6ImluZGV4LmpzIiwic291cmNlc0NvbnRlbnQiOlsiXG5jb25zdCB7dXNlRWZmZWN0LHVzZVJlZn0gPSBSZWFjdDtcblxuXG5cbmZ1bmN0aW9uIEFwcCgpIHtcbiAgICBjb25zdCByZWYgPSB1c2VSZWYobnVsbCk7XG5cbiAgdXNlRWZmZWN0KCgpID0+IHtcbiAgICBkZWJ1Z2dlcjtcbiAgICAvLyBiZWZvcmVBY3RpdmF0ZVxuICAgIGNvbnNvbGUubG9nKDEyMylcbiAgICByZWYuY3VycmVudC5mb2N1cygpO1xuICB9LCBbXSlcbiAgICByZXR1cm4gPGRpdj5cbiAgICAgICAgPGlucHV0IHJlZj17cmVmfT48L2lucHV0PlxuICAgICAgICA8cCA+SGVsbG8sIFJlYWN0IFNvdXJjZSBDb2RlITwvcD5cbiAgICAgICAgPGgzPkhlbGxvLCBSZWFjdCBTb3VyY2UgQ29kZSE8c3Bhbj4xMjM8L3NwYW4+PC9oMz5cbiAgICA8L2Rpdj5cbn1cblxuUmVhY3RET00ucmVuZGVyKDxBcHAvPiwgZG9jdW1lbnQucXVlcnlTZWxlY3RvcignI2FwcCcpKSJdfQ==`

**Comment by wangxingxing123654** [comment]
`
const {useEffect,useRef} = React;



function App() {

  useEffect(() => {
    console.log(123)
  }, [])
  useEffect(() => {
    console.log(456)
  }, [])
    return <div>
        <input ref={ref}></input>
        <p >Hello, React Source Code!</p>
        <h3>Hello, React Source Code!<span>123</span></h3>
    </div>
}

ReactDOM.render(<App/>, document.querySelector('#app'))`

**Comment by wangxingxing123654** [comment]
下面是已经更新后的代码了，但是点开vscode里的debugger，还是之前的代码

**Comment by Terry-Su** [comment]
> 下面是已经更新后的代码了，但是点开vscode里的debugger，还是之前的代码

多研究下，应该没啥问题
